on:
  push:
    paths:
    - 'A/**'
    - 'B/**'
    - 'C/**'

jobs:
  Build-Deploy:
    name: Build-Deploy
    runs-on: ubuntu-latest


    steps:
      
      - name: Checking Directory of Push
        run: |
        
          vi $GITHUB_EVENT_PATH
          ls
      - name: login to Azure
        run: |
          cd $GITHUB_EVENT_PATH
            
                          
          
