on:
  push:
    branches: [master]
    paths:
    - 'A/**'
    - 'B/**'
    - 'C/**'

jobs:
  Build-Deploy:
    name: Build-Deploy
    runs-on: ubuntu-latest


    steps:
      - run: env
      
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - name: Check commit
        uses: adityaa30/check-commit@master
      
      - name: Checking Directory of Push
        run: |
        
          
          ls
      - name: login to Azure
        run: |
          ls
            
                          
          
