on:
  push:
    paths:
    - 'A/**'
    - 'B/**'
    - 'C/**'

jobs:
  Build-Deploy:
    name: Build-Deploy
    runs-on: ubuntu-latest


    steps:
      
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      
      - name: Checking Directory of Push
        run: |
        
          
          ls
      - name: login to Azure
        run: |
          ls
            
                          
          
