on:
  push:
    branches: [ master ]

jobs:
  Build-Deploy:
    name: Build-Deploy
    runs-on: ubuntu-latest


    steps:
      
      - name: Installing Azure CLI
        run: |
        
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version
      - name: login to Azure
        run: |
          #az login
          az login --username=${{ secrets.AZURE_USERNAME }} --password=${{ secrets.AZURE_PASSWORD }}
            
                          
          
